#!/bin/bash

declare -a inputs

TMPFILE=/tmp/exip.tmp.${RANDOM}
DNSRESOLV=0
WHOIS=0
CSV=0

RESOLVESTR=""
ORG=""
NETRANGE=""

# Help Output
function Usage()
{
	echo -e ""
	echo -e "expip : Extract IP's from file"
	echo -e "=============================="
	printf "%s\t%s\n" "-h" "This menu"
	printf "%s\t%s\n" "-d" "Extract, then resolve IP's"
	printf "\n%s\n" "Any other argument is considered a file to be opened"
}

# Resolve IP
function Resolve()
{
	RESOLVESTR=$(dig -x ${1} | egrep -A1 "^\;\;\s+ANSWER" | tail -n1 | tr "\t" " " | cut -d" " -f5)

	[ "${RESOLVESTR}" = "" ] && RESOLVESTR="Not-resolvable"
}

# Whois the IP
function Whois()
{
	whois "${1}" > "${TMPFILE}.whois"

	ORG=$(grep "Organization" ${TMPFILE}.whois | tr -s " " | cut -d" " -f2-)
	NETRANGE=$(grep "NetRange" ${TMPFILE}.whois | tr -s " " | cut -d" " -f2-)

	[ -e ${TMPFILE}.whois ] && rm ${TMPFILE}.whois
}

# Extract IPs
function ExtractIPs()
{
	MAXQUAD="([0-9]|[1-9]{1,2}|1[0-9]{1,2}|2[0-4][0-9]|25[0-5])"
	EXPR="[[:space:][:punct:]]{0,1}(${MAXQUAD}\.){3}${MAXQUAD}"

	grep -o -E "${EXPR}" "${1}" | tr -d "[:blank:]" > ${TMPFILE}

	if [ ${DNSRESOLV} -ne 0 -o ${WHOIS} -ne 0 ]; then
		while read ip; do
			RESOLVESTR=""
			ORG=""; NETRANGE=""

			[ ${DNSRESOLV} -ne 0 ] && Resolve ${ip}
			[ ${WHOIS} -ne 0 ] && Whois ${ip}

			if [ ${CSV} -ne 0 ]; then
				printf "%s,%s,%s,%s\n" "${ip}" "${RESOLVESTR}" "${NETRANGE}" "${ORG}"
			else
				printf "%-15s %-40s %-33s %s\n" "${ip}" "${RESOLVESTR}" "${NETRANGE}" "${ORG}"
			fi

		done < ${TMPFILE}
	else
		cat ${TMPFILE}
	fi

	[ -e ${TMPFILE} ] && rm ${TMPFILE}
}

#
# Main Loop
#

# Process arguments
while [ ! "${1}" = "" ]; do
	case "${1}" in
	"-h")	Usage; exit 0 ;;
	"-d")	DNSRESOLV=1 ;;
	"-w")	WHOIS=1 ;;
	"-c")	CSV=1 ;;
	*)	inputs[${#inputs[@]}]="${1}" ;;
	esac

	shift 1
done

if [ ${#inputs[@]} -eq 0 ]; then
	inputs[0]="/dev/stdin"
fi

for ((index=0; index < ${#inputs[@]}; ++index)); do
	ExtractIPs "${inputs[${index}]}"
done
